version: '3.3'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: someone
      POSTGRES_PASSWORD: password
      POSTGRES_DB: somedb
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
volumes:
  pgdata: